<a href="https://colab.research.google.com/github/shreya16sharma/Machine-Learning/blob/main/basic_of_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
 
# Creating a rank 1 Array
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [ ]:
# Creating a rank 2 Array
arr2 = np.array([[1, 2, 3],
                [4, 5, 6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2.dtype

dtype('int64')

In [ ]:
# Forced Datatype
x = np.array([1, 2], dtype = np.int64) 

Math Operations on DataType array

In [ ]:
arr1 = np.array([[4, 7], [2, 6]], 
                 dtype = np.float64)
                  
# Second Array
arr2 = np.array([[3, 6], [2, 8]], 
                 dtype = np.float64) 
 
# Addition of two Arrays
Sum = np.add(arr1, arr2)

In [ ]:
# Addition of all Array elements
# using predefined sum method
Sum1 = np.sum(arr1)

In [ ]:
np.any([[True,False],[True,True]])

True

In [ ]:
np.zeros([4, 3],
         dtype = np.int32,
         order = 'f')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [ ]:
np.ones([4, 3],
        dtype = np.int32,
        order = 'f')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [ ]:
np.empty([4, 3],
         dtype = np.int32,
         order = 'f')

array([[39140960,        0,        0],
       [       0,        0,        0],
       [       0,        0,        0],
       [       0,        0,        0]], dtype=int32)

In [ ]:
var = "AmazingWorld"
 
arr = np.fromiter(var, dtype = 'U2')
arr
 

array(['A', 'm', 'a', 'z', 'i', 'n', 'g', 'W', 'o', 'r', 'l', 'd'],
      dtype='<U2')